import { useCallback, useRef, useEffect } from "react";
import type { Move } from "../types";
import { NUMBER_AUDIO_MAP, MOVE_AUDIO_MAP } from "../utils/constants";

export function useAudioSequencer({
  useVoiceRef,
  showFullNameRef,
  currentMoves,
}: {
  useVoiceRef: React.MutableRefObject<boolean>;
  showFullNameRef: React.MutableRefObject<boolean>;
  currentMoves: Move[];
}) {
  const activeAudioRef = useRef<HTMLAudioElement | null>(null);
  const audioCacheRef = useRef<Map<string, HTMLAudioElement>>(new Map());

  // 1️⃣ PRELOADER: Loads ALL combo audio into memory exactly once during initialization
  useEffect(() => {
    const cache = audioCacheRef.current;

    // A helper to prep & load a single HTMLAudioElement safely into dictionary map
    const preloadTrack = (url: string) => {
      if (!cache.has(url)) {
        const audio = new Audio();
        audio.preload = "auto";
        audio.src = url;
        audio.load(); // Forces memory cache
        cache.set(url, audio);
      }
    };

    // Preload all standard number strings (1-20 via NUMBER_WORDS)
    Object.values(NUMBER_AUDIO_MAP).forEach((filename) => {
      preloadTrack(`/voicegen/en-US-GuyNeural/${filename}`);
    });

    // Preload all named actions generated by the current moves list
    currentMoves.forEach((move) => {
      const filename = MOVE_AUDIO_MAP[move.name.toUpperCase()];
      if (filename) preloadTrack(`/voicegen/en-US-GuyNeural/${filename}`);
    });
  }, [currentMoves]);

  const stopAudio = useCallback(() => {
    if (activeAudioRef.current) {
      activeAudioRef.current.pause();
      activeAudioRef.current = null;
    }
  }, []);

  const playComboAudio = useCallback(
    (keys: number[], timeAllowedMs: number) => {
      if (!useVoiceRef.current) return;

      // Ensure we aim to finish playing all moves in AT MOST a fraction of the speed allocation.
      const maxTimePerMove = (timeAllowedMs * 0.7) / keys.length;
      // Calculate a playback rate that compresses the clips (e.g. 1.2x up to 3.0x speed)
      // Most voicegen tracks are ~0.8s long (800ms)
      const idealPlaybackRate = Math.max(1.2, Math.min(3.0, 800 / maxTimePerMove));

      const audioQueue = keys.map((k) => {
        if (showFullNameRef.current) {
          const moveName =
            currentMoves.find((m) => m.key === k)?.name ?? String(k);
          const filename = MOVE_AUDIO_MAP[moveName.toUpperCase()];
          return filename ? `/voicegen/en-US-GuyNeural/${filename}` : "";
        } else {
          const filename = NUMBER_AUDIO_MAP[k];
          return filename ? `/voicegen/en-US-GuyNeural/${filename}` : "";
        }
      });

      const playNext = (index: number) => {
        if (index >= audioQueue.length) return;

        // Retrieve preloaded audio instance directly from memory-cache
        const urlToPlay = audioQueue[index];
        if (!urlToPlay) {
          playNext(index + 1);
          return;
        }

        const audio = audioCacheRef.current.get(urlToPlay);
        if (!audio) {
          // Fallback just in case, shouldn't occur given the useEffect
          playNext(index + 1);
          return;
        }
        
        activeAudioRef.current = audio;

        // Reset the tracker head of the internal media element so it plays from the start
        audio.currentTime = 0;

        // Force it to play much faster so the whole sequence fits the speed allocation
        audio.playbackRate = idealPlaybackRate;
        audio.preservesPitch = true; // supported in modern browsers

        audio.onended = () => {
          audio.onended = null;
          playNext(index + 1);
        };
        
        audio.play().catch(() => playNext(index + 1));
      };

      playNext(0);
    },
    [currentMoves, showFullNameRef, useVoiceRef]
  );

  return { playComboAudio, stopAudio };
}
