import { useCallback, useRef, useEffect } from "react";
import type { Move, DisplayMode } from "../types";
import { NUMBER_AUDIO_MAP, MOVE_AUDIO_MAP } from "../utils/constants";

export function useAudioSequencer({
  useVoiceRef,
  displayModeRef,
  customDisplayKeysRef,
  currentMoves,
}: {
  useVoiceRef: React.MutableRefObject<boolean>;
  displayModeRef: React.MutableRefObject<DisplayMode>;
  customDisplayKeysRef: React.MutableRefObject<Set<number>>;
  currentMoves: Move[];
}) {
  const activeAudioRef = useRef<HTMLAudioElement | null>(null);
  const audioCacheRef = useRef<Map<string, HTMLAudioElement>>(new Map());
  const activeTimeoutRef = useRef<any>(null);

  // Clear any scheduled timeouts on unmount to prevent leaks
  useEffect(() => {
    return () => {
      if (activeTimeoutRef.current) {
        clearTimeout(activeTimeoutRef.current);
      }
    };
  }, []);

  // 1️⃣ PRELOADER: Loads ALL combo audio into memory exactly once during initialization
  useEffect(() => {
    const cache = audioCacheRef.current;

    // A helper to prep & load a single HTMLAudioElement safely into dictionary map
    const preloadTrack = (url: string) => {
      if (!cache.has(url)) {
        const audio = new Audio();
        audio.preload = "auto";
        audio.src = url;
        audio.load(); // Forces memory cache
        cache.set(url, audio);
      }
    };

    // Preload all standard number strings (1-20 via NUMBER_WORDS)
    Object.values(NUMBER_AUDIO_MAP).forEach((filename) => {
      preloadTrack(`/voicegen/en-US-GuyNeural/${filename}`);
    });

    // Preload all named actions generated by the current moves list
    currentMoves.forEach((move) => {
      const filename = MOVE_AUDIO_MAP[move.name.toUpperCase()];
      if (filename) preloadTrack(`/voicegen/en-US-GuyNeural/${filename}`);
    });
  }, [currentMoves]);

  const stopAudio = useCallback(() => {
    if (activeTimeoutRef.current) {
      clearTimeout(activeTimeoutRef.current);
      activeTimeoutRef.current = null;
    }
    if (activeAudioRef.current) {
      activeAudioRef.current.pause();
      activeAudioRef.current.onended = null;
      activeAudioRef.current = null;
    }
  }, []);

  const playComboAudio = useCallback(
    (keys: number[], timeAllowedMs: number) => {
      if (!useVoiceRef.current) return;

      stopAudio(); // Reset any currently running playback sequence

      // Ensure we aim to finish playing all moves in AT MOST a fraction of the speed allocation.
      const maxTimePerMove = (timeAllowedMs * 0.7) / keys.length;
      // Calculate a playback rate that compresses the clips (e.g. 1.2x up to 3.0x speed)
      // Most voicegen tracks are ~0.8s long (800ms)
      const idealPlaybackRate = Math.max(1.2, Math.min(3.0, 800 / maxTimePerMove));

      const mode = displayModeRef.current;
      const customKeys = customDisplayKeysRef.current;

      const audioQueue = keys.map((k) => {
        const useName =
          mode === "fullname" ||
          (mode === "custom" && customKeys.has(k));

        if (useName) {
          const moveName =
            currentMoves.find((m) => m.key === k)?.name ?? String(k);
          const filename = MOVE_AUDIO_MAP[moveName.toUpperCase()];
          return filename ? `/voicegen/en-US-GuyNeural/${filename}` : "";
        } else {
          const filename = NUMBER_AUDIO_MAP[k];
          return filename ? `/voicegen/en-US-GuyNeural/${filename}` : "";
        }
      });

      const playNext = (index: number) => {
        if (index >= audioQueue.length) return;

        // Retrieve preloaded audio instance directly from memory-cache
        const urlToPlay = audioQueue[index];
        if (!urlToPlay) {
          playNext(index + 1);
          return;
        }

        const audio = audioCacheRef.current.get(urlToPlay);
        if (!audio) {
          // Fallback just in case, shouldn't occur given the useEffect
          playNext(index + 1);
          return;
        }
        
        activeAudioRef.current = audio;

        // Reset the tracker head of the internal media element so it plays from the start
        audio.currentTime = 0;

        // Force it to play much faster so the whole sequence fits the speed allocation
        audio.playbackRate = idealPlaybackRate;
        audio.preservesPitch = true; // supported in modern browsers

        audio.onended = () => {
          audio.onended = null;
          
          let delay = 0;
          if (index < keys.length - 1) {
            const currentKey = keys[index];
            const nextKey = keys[index + 1];
            const currentMove = currentMoves.find(m => m.key === currentKey);
            const nextMove = currentMoves.find(m => m.key === nextKey);
            const curName = currentMove?.name.toUpperCase() || "";
            const nextName = nextMove?.name.toUpperCase() || "";

            // Double-up compression: identical consecutive moves play rapid-fire
            if (curName === nextName && curName !== "") {
              delay = 0;
            } else {
              delay = 100; // standard space between voice cues
            }

            // High commitment extra padding (kicks, knees, elbows, defenses, heavy punches)
            const highCommitmentSuffixes = [
              "KICK", "TEEP", "KNEE", "ELBOW", "TAKEDOWN", "SPRAWL", "OVERHAND", "SPINNING"
            ];
            const isHighCommitment = highCommitmentSuffixes.some(suffix => curName.includes(suffix));
            if (isHighCommitment) {
              if (curName.includes("TAKEDOWN")) {
                delay += 1000;
              } else if (curName.includes("SPRAWL")) {
                delay += 800;
              } else {
                delay += 400; // standard kick/knee/elbow padding
              }
            }
          }

          if (delay > 0) {
            activeTimeoutRef.current = window.setTimeout(() => {
              activeTimeoutRef.current = null;
              playNext(index + 1);
            }, delay);
          } else {
            playNext(index + 1);
          }
        };
        
        audio.play().catch(() => playNext(index + 1));
      };

      playNext(0);
    },
    [currentMoves, displayModeRef, customDisplayKeysRef, useVoiceRef, stopAudio]
  );

  return { playComboAudio, stopAudio };
}
